name: Setup Monorepo
description: Prepare the monorepo for any automated action(s)

inputs:
  node-version:
    description: Version of Node to use
    default: 16.x

  eas-version:
    description: Version of EAS CLI to use
    default: latest

  expo-version:
    description: Version of Expo CLI to use
    default: latest

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v7
      with:
        eas-version: ${{ inputs.eas-version }}
        expo-version: ${{ inputs.expo-version }}
        token: ${{ inputs.expo-token }}

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --check-files
      shell: bash

    - name: 👷 Build packages
      run: yarn build
      shell: bash
